# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZVX59jD3wdMu0-_46TVrVxoNhm-GGce
"""

print("SEJA BEM-VINDO(A) AO VALIDADOR DE CPF!")
cpf = input("PARA INICIAR, DIGITE O SEU CPF: ")#090.535.554-71
cpf = cpf.replace(".","")
cpf = cpf.replace("-","")
if len(cpf) == 11:  
  if (cpf) == "00000000000" or (cpf) == "11111111111" or (cpf) == "22222222222" or (cpf) == "333333333333" or (cpf) == "44444444444" or (cpf) == "55555555555" or (cpf) == "66666666666" or (cpf) == "77777777777" or (cpf) == "88888888888" or (cpf) == "99999999999": 
    print("CPF INVÁLIDO!")
  else: 
    contador = 0
    GuardaDigito = 0
    multiplicar = 0
    total = 0
    valida = 0
    num = 10
    for contar in cpf:  
      GuardaDigito = int(cpf[contador])
      contador = contador + 1
      if (num >= 2):  
        multiplicar = GuardaDigito * num
        total = total + multiplicar
        num = num - 1 
    valida = total * 10 % 11
    if (valida == int(cpf[9])): 
      contador = 0
      GuardaDigito = 0
      multiplicar = 0
      total = 0
      valida = 0
      num = 11
      for contar in cpf:  
        GuardaDigito = int(cpf[contador])
        contador = contador + 1
        if (num >= 2):  
          multiplicar = GuardaDigito * num
          total = total + multiplicar
          num = num - 1 
      valida = total * 10 % 11
      if (valida == int(cpf[10])):  
        print("CPF É VÁLIDO")
      else: 
        print("CPF INVÁLIDO")
    else: 
      print("CPF INVÁLIDO")
else: 
  print("CPF INVÁLIDO!")